version: '3.5'
name: 'nono'
networks:
  nono.net:
    driver: bridge
services:

  #############################
  ### Web with Apache ###
  #############################

  web:
    image: httpd:latest
    ports:
      - "38209:80"
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache-iutnc.univ-lorraine.fr:3128
    volumes:
      - ../FrontEndNonoLeRobot/dist:/usr/local/apache2/htdocs/geoquizz
    networks:
      - nono.net

  #############################
  ### Gateway               ###
  #############################
  gateway:
    image: 'canals/php:8.2'
    env_file: ./auth.env
    ports:
      - '35200:80'
    volumes:
      - ../api.nono/gateway:/var/www/
      - ../api.nono/gateway/public:/var/www/html
    working_dir: /var/www
    networks:
      - nono.net
    command: >
      bash -c "composer install && composer update && apache2-foreground"

  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '8081:8080' ## 8081 40510
    networks:
      - nono.net

  nono.services.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./services.env
    ports:
      - '3311:3306' ## 40509
    networks:
      - nono.net
    volumes:
      - ../api.nono/services.nono/sql:/var/sql
      - ../api.nono/services.nono/sql:/docker-entrypoint-initdb.d

  api.services.nono:
    image: node:alpine
    working_dir: /usr/app
    command: sh -c "npm i && npm run dev" #for development only
    #command: sh -c "npm i && npm start" #for production only
    volumes:
      - ../api.nono/services.nono:/usr/app
    ports:
      - '3333:3333'
    networks:
      - nono.net
    env_file:
      - ./services.env
    depends_on:
      - nono.services.db


  ######################################
  ###  AUTH Service : service d'authentification JWT
  ###  api api.auth : auth, check, refresh de token JWT
  ###  utilise sa propre base de données
  ######################################
  api.auth.nono:
    image: 'canals/php:8.2'
    env_file: ./auth.env
    ports:
      - '2082:80' ## 2082 45053
      - '1444:443' ## 1444 45054
    volumes:
      - ../api.nono/auth.nono:/var/www/
      - ../api.nono/auth.nono/public:/var/www/html
      - ./auth.env:/config/.env
    working_dir: /var/www
    networks:
      - nono.net
    depends_on:
      - nono.auth.db
    command: >
      bash -c "composer install && composer update && apache2-foreground"

  nono.auth.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./auth.env
    ports:
      - '45055:3306' ## 3309
    networks:
      - nono.net
    volumes:
      - ../api.nono/auth.nono/sql:/var/sql
      - ../api.nono/auth.nono/sql:/docker-entrypoint-initdb.d

  nono.environnement.db:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    networks:
      - nono.net
    volumes:
      - ../api.nono/environnement.nono/data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"

  cache:
    image: redis:6
    networks:
      - nono.net

  directus:
    image: directus/directus:10.9.0
    ports:
      - '8055:8055'
    volumes:
      - ../api.nono/environnement.nono/uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - nono.environnement.db
    networks:
      - nono.net
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "pg"
      DB_HOST: "nono.environnement.db"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "false"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"