version: '3'
networks:
  nono.net:
    driver: bridge
services:

  nono.db:
    image: 'mariadb:latest'
    env_file: db.conf.ini
    ports:
      - '3306:3306'
    networks:
      - nono.net

  nono.adminer:
    image: 'adminer:latest'
    ports:
      - '8080:8080'
    networks:
      - nono.net
