version: '3.5'
name: 'nono'
networks:
  nono.net:
    driver: bridge
services:

  #############################
  ### Web with Apache ###
  #############################

  web:
    image: node:alpine
    ports:
      - "38209:5173"
    volumes:
      - ../web:/usr/local/nono
    networks:
      - nono.net
    working_dir: /usr/local/nono
    command: sh -c "npm i && npm run dev -- --host"

  #############################
  ### Gateway               ###
  #############################
  gateway:
    image: 'canals/php:8.2'
    env_file: ./auth.env
    ports:
      - '38210:80'
    volumes:
      - ../api.nono/gateway:/var/www/
      - ../api.nono/gateway/public:/var/www/html
    working_dir: /var/www
    networks:
      - nono.net

  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '40510:8081' ## 8081 40510
    networks:
      - nono.net

  nono.services.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./services.env
    ports:
      - '40509:3306' ## 40509
    networks:
      - nono.net
    volumes:
      - ../api.nono/services.nono/sql:/var/sql
      - ../api.nono/services.nono/sql:/docker-entrypoint-initdb.d

  api.services.nono:
    image: node:alpine
    working_dir: /usr/app
    command: sh -c "npm i && npm run dev" #for development only
    #command: sh -c "npm i && npm start" #for production only
    volumes:
      - ../api.nono/services.nono:/usr/app
    ports:
      - '40508:3333'
    networks:
      - nono.net
    env_file:
      - ./services.env
    depends_on:
      - nono.services.db


  ######################################
  ###  AUTH Service : service d'authentification JWT
  ###  api api.auth : auth, check, refresh de token JWT
  ###  utilise sa propre base de données
  ######################################
  api.auth.nono:
    image: 'canals/php:8.2'
    env_file: ./auth.env
    ports:
      - '45053:2082' ## 2082 45053
      - '54054:1444' ## 1444 45054
    volumes:
      - ../api.nono/auth.nono:/var/www/
      - ../api.nono/auth.nono/public:/var/www/html
      - ./auth.env:/config/.env
    working_dir: /var/www
    networks:
      - nono.net
    depends_on:
      - nono.auth.db
    command: >
      bash -c "composer install && composer update && apache2-foreground"

  nono.auth.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./auth.env
    ports:
      - '45055:3309' ## 3309
    networks:
      - nono.net
    volumes:
      - ../api.nono/auth.nono/sql:/var/sql
      - ../api.nono/auth.nono/sql:/docker-entrypoint-initdb.d